Update workflow-session.yml

diff --git a/.github/workflows/workflow-session.yml b/.github/workflows/workflow-session.yml
--- a/.github/workflows/workflow-session.yml
+++ b/.github/workflows/workflow-session.yml
@@ -47,8 +47,8 @@ jobs:
       fail-fast: false
       max-parallel: 1
       matrix:
-        python-version: [3.8, 3.9]       
-        python-venv: ["","venv"]     
+        python-version: [3.8] #, 3.9]       
+        python-venv: [""]     #  ,"venv"]     
     runs-on: ${{ inputs.os }}
     timeout-minutes: 60
     steps:
@@ -58,6 +58,8 @@ jobs:
           python-venv: ${{ matrix.python-venv }}
           gridai-username: ${{ secrets.gridai-username }} 
           gridai-key: ${{ secrets.gridai-key }} 
+
+      # create
       - id: gridai-obj-create
         run: |
           export GRID_ARGS=""
@@ -78,7 +80,51 @@ jobs:
       - run: |
           if [ -z "$(echo ${{ steps.gridai-obj-status.outputs.obj-summary }} | grep -i 'running')" ]; then
             exit 1
-          fi             
+          fi
+
+      # pause
+      - id: gridai-obj-create-2
+          gridai.py cli "grid session pause ${{ steps.gridai-obj-create.outputs.name }}"
+      - id: gridai-obj-status-2
+        run: |
+          gridai.py session ${{ steps.gridai-obj-create.outputs.name }} --obj_status_expr 'paused|failed' --gha True
+      - run: |
+          if [ -z "$(echo ${{ steps.gridai-obj-status-2.outputs.obj-summary }} | grep -i 'paused')" ]; then
+            exit 1
+          fi
+
+      # resume
+      - id: gridai-obj-create-3
+          gridai.py cli "grid session resume ${{ steps.gridai-obj-create.outputs.name }}"
+      - id: gridai-obj-status-3
+        run: |
+          gridai.py session ${{ steps.gridai-obj-create.outputs.name }} --obj_status_expr 'running|failed' --gha True
+      - run: |
+          if [ -z "$(echo ${{ steps.gridai-obj-status-3.outputs.obj-summary }} | grep -i 'running')" ]; then
+            exit 1
+          fi
+
+      # run commands, scp to and from
+      - run: |
+          # run some commands
+          grid session ssh ${{ steps.gridai-obj-create.outputs.name }} "hostname; conda env list" | tee grid.session.ssh.1.log
+          # scp to remote
+          scp grid.session.ssh.1.log ${{ steps.gridai-obj-create.outputs.name }}:.
+          # verify transfer
+          grid session ssh ${{ steps.gridai-obj-create.outputs.name }} "ls grid.session.ssh.1.log" | tee grid.session.ssh.2.log
+          if [ -z "$(grep grid.session.ssh.1.log grid.session.ssh.2.log)" ]; then
+            echo "Error: file grid.session.ssh.1.log not found in remote"
+            exit 1
+          fi
+          # scp from remote
+          scp ${{ steps.gridai-obj-create.outputs.name }}:grid.session.ssh.1.log remote.grid.session.ssh.1.log
+          diff grid.session.ssh.1.log remote.grid.session.ssh.1.log
+          if [ $? -ne 0 ]; then
+            echo "Error: grid.session.ssh.1.log remote.grid.session.ssh.1.log different"
+            exit 1
+          fi
+
+      # delete
       - id: gridai-obj-delete
         run: |
           gridai.py cli "grid session delete ${{ steps.gridai-obj-create.outputs.name }}" --gha True
